### ISSUE TITLE
Disable warnings in commandline

### ISSUE THREAD

**Issue by BlaM** [gavinhungry/closure-compiler-service#3]
When usind cli.js - how do I disable warnings?

**Comment by gavinhungry** [comment]
@BlaM, the warnings are  written to `stderr`, so it shouldn't affect your piped output (the code is written to `stdout`).

But, I added a `-q, --quiet` option for you in [0.6.0](https://github.com/gavinhungry/closure-compiler-service/tree/0.6.0) anyway:
```
Usage: closure-service [options] <file>

Options:

  -h, --help     output usage information
  -V, --version  output the version number
  -q, --quiet    no warning output
```
